version: "3.8"
services:
  web:
    build:
      context: .
      target: web
      args:
        RAILS_ENV: "development"
    command: bin/dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
       - .env.development.local
    environment:
      # TODO: Update dfsseta-apply-for-landing with application name
      DATABASE_URL: postgres://postgres:password@db:5432/dfsseta-apply-for-landing-development
      AUTOMATICALLY_FIX_LINTING: "true"
    volumes:
      - .:/srv/app
    tty: true
    stdin_open: true
    networks:
      - dev

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      # TODO: Update dfsseta-apply-for-landing with application name
      POSTGRES_DB: dfsseta-apply-for-landing-development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
