services:
  test:
    build:
      context: .
      target: test
      args:
        RAILS_ENV: "test"
      cache_from:
        - app_test:latest
    image: app_test
    command: bundle exec rake
    ports:
      - "3000:3000"
    depends_on:
      - test-db
    env_file:
       - .env.test
    environment:
      DATABASE_URL: postgres://postgres:password@test-db:5432/app-test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      SECRET_KEY_BASE: secret
      CI: "true"
    networks:
      - test-ci

  test-db:
    image: postgres@sha256:6efd0df010dc3cb40d5e33e3ef84acecc5e73161bd3df06029ee8698e5e12c60
    environment:
      POSTGRES_DB: app-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - test-ci

networks:
  test-ci:
