---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/landing-applications":
    get:
      summary: Retrieves a list of landing applications
      tags:
        - Landing applications
      responses:
        "200":
          description: success
          content:
            application/json:
              examples:
                test_example:
                  value:
                    - application_id: f5f81284-e377-4017-aab1-1efac2119a2c
                      destination: Planet X
                      pilot:
                        name: Fred Smith
                        email: fred@example.com
                        licence_id: 1233ABC00123
                      permit_issued_at: "2024-09-18T07:53:21Z"
                      permit_id: LP-3522-HNWD
                      spacecraft_registration_id: ABC123A
                      landing_date: "2024-10-11"
                      departure_date: "2024-10-18"
servers:
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: localhost
  - url: http://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
