---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/landing-applications":
    get:
      summary: Retrieves a list of landing applications
      tags:
        - Landing applications
      security:
        - api_key: []
      responses:
        "200":
          description: success
          content:
            application/json:
              examples:
                test_example:
                  value:
                    - application_id: f5f81284-e377-4017-aab1-1efac2119a2c
                      pilot:
                        name: Fred Smith
                        email: fred@example.com
                        licence_id: 1233ABC00123
                      permit_issued_at: "2024-09-24T10:28:31Z"
                      permit_id: LP-3522-HNWD
                      destination: Planet X
                      landing_date: "2024-10-17"
                      departure_date: "2024-10-24"
                      spacecraft_registration_id: ABC123A
        "401":
          description: invalid credentials
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
security:
  - api_key: []
servers:
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: localhost
  - url: http://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
