#!/bin/sh

# Setup environment for CI to run tests. This is primarily designed to run on
# the continuous integration server.

set -e

docker version

COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 DOCKER_CLI_EXPERIMENTAL=enabled docker-compose -f docker-compose.ci.yml -p app buildx
